version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      # Azure configuration (Defaults to false)
      - AZURE_CLOUD=false
      # - AZURE_CLIENT_ID=
      # - AZURE_PG_HOST=
      # - AZURE_PG_PORT=
      # - AZURE_PG_DATABASE=

      # Auth configuration
      - BETTER_AUTH_SECRET=${BETTER_AUTH_SECRET}
      - BETTER_AUTH_URL=${BETTER_AUTH_URL}
      - BETTER_AUTH_TELEMETRY=0

      # OAuth providers
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - DISCORD_CLIENT_ID=${DISCORD_CLIENT_ID}
      - DISCORD_CLIENT_SECRET=${DISCORD_CLIENT_SECRET}

      # Database
      # Connect to the postgres service defined below
      - DATABASE_URL=${DATABASE_URL:-postgresql://postgres:postgres@postgres:5432/better_auth}
      - RUN_MIGRATIONS=${RUN_MIGRATIONS:-true}

      # App configuration
      - ORIGINS=${ORIGINS}
      - COOKIE_DOMAIN=${COOKIE_DOMAIN}
      - NODE_ENV=${NODE_ENV}
      - EMAIL_PASSWORD_AUTH=${EMAIL_PASSWORD_AUTH}
      - LINK_ACCOUNTS=${LINK_ACCOUNTS}
    depends_on:
      - postgres
    restart: unless-stopped

  postgres:
    image: postgres:alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=better_auth
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data:
